name: Springit

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */5 * * *'  # 每5小时触发一次

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要写权限来推送更改

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.name "Tra321"
        git config --global user.email "atraa0621@gmail.com"

    - name: Pull latest changes
      run: |
        git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git pull origin master  # 拉取远程 master 分支的最新更改

    - name: Random delay
      run: sleep $((RANDOM % 1800)) # 随机延迟0-30分钟
      shell: bash
      
    - name: Auto-green 
      run: |
        git pull --rebase origin master
        git commit --allow-empty -m "Auto-commit by GitHub Actions"
        git push origin master  # 推送到远程 master 分支
